import { Product, ShippingAddress, Review } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: '简约纯棉T恤',
    description: '采用100%纯棉面料，柔软舒适，透气性好。简约设计，适合日常穿搭。',
    price: 89.9,
    originalPrice: 129.9,
    images: [
      'https://via.placeholder.com/400x400/FF6B6B/FFFFFF?text=T-Shirt+1',
      'https://via.placeholder.com/400x400/4ECDC4/FFFFFF?text=T-Shirt+2',
      'https://via.placeholder.com/400x400/45B7D1/FFFFFF?text=T-Shirt+3',
    ],
    category: 'clothing',
    rating: 4.5,
    reviewCount: 128,
    stock: 50,
    sku: 'TS001',
    variants: [
      { id: '1-1', name: '白色 / S', price: 89.9, stock: 20, attributes: { color: '白色', size: 'S' } },
      { id: '1-2', name: '白色 / M', price: 89.9, stock: 15, attributes: { color: '白色', size: 'M' } },
      { id: '1-3', name: '白色 / L', price: 89.9, stock: 15, attributes: { color: '白色', size: 'L' } },
      { id: '1-4', name: '黑色 / S', price: 89.9, stock: 10, attributes: { color: '黑色', size: 'S' } },
      { id: '1-5', name: '黑色 / M', price: 89.9, stock: 8, attributes: { color: '黑色', size: 'M' } },
    ],
  },
  {
    id: '2',
    name: '无线蓝牙耳机',
    description: '高保真音质，降噪功能，续航时间长达20小时。轻巧设计，佩戴舒适。',
    price: 299.0,
    originalPrice: 399.0,
    images: [
      'https://via.placeholder.com/400x400/96CEB4/FFFFFF?text=Earphones',
      'https://via.placeholder.com/400x400/FFEAA7/FFFFFF?text=Earphones+2',
    ],
    category: 'electronics',
    rating: 4.8,
    reviewCount: 256,
    stock: 30,
    sku: 'EL001',
    variants: [
      { id: '2-1', name: '白色', price: 299.0, stock: 15, attributes: { color: '白色' } },
      { id: '2-2', name: '黑色', price: 299.0, stock: 15, attributes: { color: '黑色' } },
    ],
  },
  {
    id: '3',
    name: '运动水壶',
    description: '不锈钢材质，保温保冷，防漏设计。容量750ml，适合运动户外使用。',
    price: 59.9,
    images: [
      'https://via.placeholder.com/400x400/DDA0DD/FFFFFF?text=Bottle',
      'https://via.placeholder.com/400x400/98D8C8/FFFFFF?text=Bottle+2',
    ],
    category: 'sports',
    rating: 4.3,
    reviewCount: 89,
    stock: 100,
    sku: 'SP001',
    variants: [
      { id: '3-1', name: '蓝色', price: 59.9, stock: 40, attributes: { color: '蓝色' } },
      { id: '3-2', name: '绿色', price: 59.9, stock: 35, attributes: { color: '绿色' } },
      { id: '3-3', name: '红色', price: 59.9, stock: 25, attributes: { color: '红色' } },
    ],
  },
  {
    id: '4',
    name: '便携充电宝',
    description: '20000mAh大容量，支持快充，双输出接口。小巧便携，出行必备。',
    price: 159.0,
    originalPrice: 199.0,
    images: [
      'https://via.placeholder.com/400x400/F7DC6F/FFFFFF?text=PowerBank',
      'https://via.placeholder.com/400x400/BB8FCE/FFFFFF?text=PowerBank+2',
    ],
    category: 'electronics',
    rating: 4.6,
    reviewCount: 187,
    stock: 45,
    sku: 'EL002',
  },
  {
    id: '5',
    name: '休闲帆布鞋',
    description: '经典帆布鞋款，舒适透气，防滑鞋底。多色可选，百搭时尚。',
    price: 129.0,
    images: [
      'https://via.placeholder.com/400x400/85C1E9/FFFFFF?text=Shoes',
      'https://via.placeholder.com/400x400/F8C471/FFFFFF?text=Shoes+2',
    ],
    category: 'shoes',
    rating: 4.4,
    reviewCount: 94,
    stock: 60,
    sku: 'SH001',
    variants: [
      { id: '5-1', name: '白色 / 38', price: 129.0, stock: 20, attributes: { color: '白色', size: '38' } },
      { id: '5-2', name: '白色 / 39', price: 129.0, stock: 15, attributes: { color: '白色', size: '39' } },
      { id: '5-3', name: '黑色 / 38', price: 129.0, stock: 15, attributes: { color: '黑色', size: '38' } },
      { id: '5-4', name: '黑色 / 39', price: 129.0, stock: 10, attributes: { color: '黑色', size: '39' } },
    ],
  },
  {
    id: '6',
    name: '智能手环',
    description: '心率监测，睡眠跟踪，消息提醒。防水设计，续航7天。',
    price: 199.0,
    originalPrice: 249.0,
    images: [
      'https://via.placeholder.com/400x400/82E0AA/FFFFFF?text=SmartBand',
      'https://via.placeholder.com/400x400/E59866/FFFFFF?text=SmartBand+2',
    ],
    category: 'electronics',
    rating: 4.7,
    reviewCount: 312,
    stock: 25,
    sku: 'EL003',
    variants: [
      { id: '6-1', name: '黑色', price: 199.0, stock: 10, attributes: { color: '黑色' } },
      { id: '6-2', name: '蓝色', price: 199.0, stock: 8, attributes: { color: '蓝色' } },
      { id: '6-3', name: '粉色', price: 199.0, stock: 7, attributes: { color: '粉色' } },
    ],
  },
];

export const mockCategories = [
  { id: 'all', name: '全部', count: mockProducts.length },
  { id: 'clothing', name: '服装', count: mockProducts.filter(p => p.category === 'clothing').length },
  { id: 'electronics', name: '电子产品', count: mockProducts.filter(p => p.category === 'electronics').length },
  { id: 'sports', name: '运动户外', count: mockProducts.filter(p => p.category === 'sports').length },
  { id: 'shoes', name: '鞋类', count: mockProducts.filter(p => p.category === 'shoes').length },
];

export const mockShippingAddresses: ShippingAddress[] = [
  {
    id: '1',
    name: '张三',
    phone: '13800138000',
    province: '北京市',
    city: '北京市',
    district: '朝阳区',
    address: '建国路88号SOHO现代城A座',
    postalCode: '100022',
    isDefault: true,
  },
  {
    id: '2',
    name: '李四',
    phone: '13900139000',
    province: '上海市',
    city: '上海市',
    district: '浦东新区',
    address: '陆家嘴环路100号',
    postalCode: '200120',
    isDefault: false,
  },
];

export const mockShippingMethods = [
  { id: 'standard', name: '标准配送', cost: 10.0, estimatedDays: '3-5个工作日' },
  { id: 'express', name: '快递配送', cost: 20.0, estimatedDays: '1-2个工作日' },
  { id: 'free', name: '免邮配送', cost: 0.0, estimatedDays: '5-7个工作日', minOrder: 199.0 },
];

export const mockPaymentMethods = [
  { id: 'alipay', name: '支付宝', icon: '💰' },
  { id: 'wechat', name: '微信支付', icon: '💳' },
  { id: 'simulated', name: '模拟支付', icon: '🔄' },
];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    productId: '1',
    userId: 'user-1',
    userName: '张三',
    userAvatar: 'https://via.placeholder.com/40x40/FF6B6B/FFFFFF?text=张',
    rating: 5,
    title: '质量非常好',
    comment: '面料很舒服，尺寸标准，洗了几次也没有变形。非常满意！',
    createdAt: '2024-03-10T14:30:00Z',
    helpfulCount: 24,
    verifiedPurchase: true,
    images: ['https://via.placeholder.com/200x200/FF6B6B/FFFFFF?text=Review+1']
  },
  {
    id: 'review-2',
    productId: '1',
    userId: 'user-2',
    userName: '李四',
    userAvatar: 'https://via.placeholder.com/40x40/4ECDC4/FFFFFF?text=李',
    rating: 4,
    title: '性价比高',
    comment: '价格实惠，质量对得起价格。白色稍微有点透，建议穿浅色内衣。',
    createdAt: '2024-03-05T09:15:00Z',
    helpfulCount: 18,
    verifiedPurchase: true,
    images: []
  },
  {
    id: 'review-3',
    productId: '1',
    userId: 'user-3',
    userName: '王五',
    userAvatar: 'https://via.placeholder.com/40x40/45B7D1/FFFFFF?text=王',
    rating: 5,
    title: '非常满意',
    comment: '买了黑色M码，很合身。面料柔软，做工精细。会回购！',
    createdAt: '2024-02-28T16:45:00Z',
    helpfulCount: 32,
    verifiedPurchase: true,
    images: ['https://via.placeholder.com/200x200/45B7D1/FFFFFF?text=Review+3']
  },
  {
    id: 'review-4',
    productId: '1',
    userId: 'user-4',
    userName: '赵六',
    userAvatar: 'https://via.placeholder.com/40x40/96CEB4/FFFFFF?text=赵',
    rating: 3,
    title: '一般般',
    comment: '面料还可以，但尺寸偏小。我平时穿M码，这个M码有点紧。建议买大一码。',
    createdAt: '2024-02-20T11:20:00Z',
    helpfulCount: 9,
    verifiedPurchase: true,
    images: []
  },
  {
    id: 'review-5',
    productId: '1',
    userId: 'user-5',
    userName: '钱七',
    userAvatar: 'https://via.placeholder.com/40x40/F7DC6F/FFFFFF?text=钱',
    rating: 4,
    title: '物有所值',
    comment: '在这个价位算是很不错的T恤了。颜色正，不起球。已经推荐给朋友了。',
    createdAt: '2024-02-15T13:10:00Z',
    helpfulCount: 15,
    verifiedPurchase: true,
    images: []
  },
  {
    id: 'review-6',
    productId: '2',
    userId: 'user-6',
    userName: '孙八',
    userAvatar: 'https://via.placeholder.com/40x40/BB8FCE/FFFFFF?text=孙',
    rating: 5,
    title: '音质超棒',
    comment: '蓝牙连接稳定，音质清晰，续航时间长。性价比很高！',
    createdAt: '2024-03-12T10:30:00Z',
    helpfulCount: 42,
    verifiedPurchase: true,
    images: ['https://via.placeholder.com/200x200/BB8FCE/FFFFFF?text=Review+6']
  },
  {
    id: 'review-7',
    productId: '2',
    userId: 'user-7',
    userName: '周九',
    userAvatar: 'https://via.placeholder.com/40x40/85C1E9/FFFFFF?text=周',
    rating: 4,
    title: '不错的产品',
    comment: '佩戴舒适，降噪效果不错。充电盒有点大，携带不太方便。',
    createdAt: '2024-03-08T15:45:00Z',
    helpfulCount: 21,
    verifiedPurchase: true,
    images: []
  },
  {
    id: 'review-8',
    productId: '3',
    userId: 'user-8',
    userName: '吴十',
    userAvatar: 'https://via.placeholder.com/40x40/82E0AA/FFFFFF?text=吴',
    rating: 5,
    title: '保温效果很好',
    comment: '24小时保温没问题，设计简约大方。密封性很好，不会漏水。',
    createdAt: '2024-03-14T09:20:00Z',
    helpfulCount: 28,
    verifiedPurchase: true,
    images: ['https://via.placeholder.com/200x200/82E0AA/FFFFFF?text=Review+8']
  }
];